// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx4TdUHZ97HPn9A79ZhRwrzkYswObhwBM',
    appId: '1:511658746188:web:6681d4f93349d68d57afe9',
    messagingSenderId: '511658746188',
    projectId: 'tictactoewuthfire1112',
    authDomain: 'tictactoewuthfire1112.firebaseapp.com',
    storageBucket: 'tictactoewuthfire1112.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMZGCHp7giAD1-k5pit8SpJd03YgUcrfY',
    appId: '1:511658746188:android:423cab9fa023131957afe9',
    messagingSenderId: '511658746188',
    projectId: 'tictactoewuthfire1112',
    storageBucket: 'tictactoewuthfire1112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS8K4F7FQ3Jucb18RhBz7VWHZOu-7bSkQ',
    appId: '1:511658746188:ios:e8009b8d044a873257afe9',
    messagingSenderId: '511658746188',
    projectId: 'tictactoewuthfire1112',
    storageBucket: 'tictactoewuthfire1112.appspot.com',
    iosClientId: '511658746188-hh7dh11cvnfd5r4n0cmrgbv7tgvcfjtm.apps.googleusercontent.com',
    iosBundleId: 'com.fluttertictictoe111.tictictoeproject1223',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS8K4F7FQ3Jucb18RhBz7VWHZOu-7bSkQ',
    appId: '1:511658746188:ios:e8009b8d044a873257afe9',
    messagingSenderId: '511658746188',
    projectId: 'tictactoewuthfire1112',
    storageBucket: 'tictactoewuthfire1112.appspot.com',
    iosClientId: '511658746188-hh7dh11cvnfd5r4n0cmrgbv7tgvcfjtm.apps.googleusercontent.com',
    iosBundleId: 'com.fluttertictictoe111.tictictoeproject1223',
  );
}
